### ISSUE TITLE
Issues with timezones

### ISSUE THREAD

**Issue by lazyguru** [testdrivenio/masonite-on-docker#1]
When using these containers and trying to use pendulum there are issues with timezones.  Eg, a call to:

```
docker-compose exec web craft tinker
import pendulum
pendulum.now()
```

Throws the error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pendulum/pendulum.py", line 277, in now
    dt = datetime.datetime.now(cls._local_timezone())
  File "/usr/local/lib/python3.8/site-packages/pendulum/pendulum.py", line 93, in _local_timezone
    return local_timezone()
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/__init__.py", line 30, in local_timezone
    return LocalTimezone.get()
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 25, in get
    name = cls.get_local_tz_name()
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 60, in get_local_tz_name
    return getattr(cls, 'get_tz_name_for_{}'.format(os))()
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 169, in get_tz_name_for_unix
    raise RuntimeError('Can not find any timezone configuration')
RuntimeError: Can not find any timezone configuration
```
Calling `pendulum.now(tz='UTC')` or `pendulum.now(tz='America/New_York')` works properly so the issue is with pendulum being able to resolve the default timezone.  See https://github.com/miracle2k/k8s-snapshots/issues/83 for a similar issue.

**Comment by mjhea0** [comment]
Thanks for letting me know.
